//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amlak.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MaklerEntities : DbContext
    {
        public MaklerEntities()
            : base("name=MaklerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Amlak> Amlak { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Elan> Elan { get; set; }
        public virtual DbSet<Personal> Personal { get; set; }
    }
}
